# Generated by Django 4.2.23 on 2025-08-21 10:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)])),
                ('gender_identity', models.CharField(blank=True, max_length=100)),
                ('pronoun', models.CharField(blank=True, max_length=50)),
                ('legal_name', models.CharField(blank=True, max_length=100)),
                ('birth_name', models.CharField(blank=True, max_length=100)),
                ('native_name', models.CharField(blank=True, max_length=100)),
                ('home_address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email_visibility', models.CharField(choices=[('public', 'Public'), ('admin', 'Admin Only'), ('private', 'Private')], default='private', max_length=10)),
                ('occupation_visibility', models.CharField(choices=[('public', 'Public'), ('admin', 'Admin Only'), ('private', 'Private')], default='public', max_length=10)),
                ('age_visibility', models.CharField(choices=[('public', 'Public'), ('admin', 'Admin Only'), ('private', 'Private')], default='private', max_length=10)),
                ('gender_identity_visibility', models.CharField(choices=[('public', 'Public'), ('admin', 'Admin Only'), ('private', 'Private')], default='private', max_length=10)),
                ('pronoun_visibility', models.CharField(choices=[('public', 'Public'), ('admin', 'Admin Only'), ('private', 'Private')], default='public', max_length=10)),
                ('legal_name_visibility', models.CharField(choices=[('public', 'Public'), ('admin', 'Admin Only'), ('private', 'Private')], default='public', max_length=10)),
                ('birth_name_visibility', models.CharField(choices=[('public', 'Public'), ('admin', 'Admin Only'), ('private', 'Private')], default='private', max_length=10)),
                ('native_name_visibility', models.CharField(choices=[('public', 'Public'), ('admin', 'Admin Only'), ('private', 'Private')], default='public', max_length=10)),
                ('home_address_visibility', models.CharField(choices=[('public', 'Public'), ('admin', 'Admin Only'), ('private', 'Private')], default='private', max_length=10)),
                ('emergency_contact_visibility', models.CharField(choices=[('public', 'Public'), ('admin', 'Admin Only'), ('private', 'Private')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('consent_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_owner', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'requester', 'field_name')},
            },
        ),
    ]
