# Generated by Django 4.2.23 on 2025-08-29 12:07

import IdentityAndProfileManager.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IdentityAndProfileManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprofile',
            name='email',
            field=IdentityAndProfileManager.models.EncryptedCharField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='emergency_contact',
            field=IdentityAndProfileManager.models.EncryptedCharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='home_address',
            field=IdentityAndProfileManager.models.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='phone_number',
            field=IdentityAndProfileManager.models.EncryptedCharField(blank=True, max_length=20),
        ),
    ]
